import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
print("series A:")
print(a)
print("\n series B:")
print(b)
non_com=a[~a.isin(b)].tolist()+b[~b.isin(a)].tolist()
print("Items not common to both series:")
print(non_com)
print("\n smallest element in series A:\n",a.min())
print("\n largest element in series A:\n",a.max())
print("\n sum of series B:",b.sum())
print("\n average of series A:",a.mean())
print("\n median of series B:",b.median())